//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvertimeCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestDish
    {
        public int Id { get; set; }
        public int GuestId { get; set; }
        public int DishId { get; set; }
        public Nullable<int> DishStatusId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual DishStatus DishStatus { get; set; }
    }
}
