//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvertimeCafe.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OvertimeDbEntities : DbContext
    {
        public OvertimeDbEntities()
            : base("name=OvertimeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dish> Dish { get; set; }
        public DbSet<Guest> Guest { get; set; }
        public DbSet<GuestDish> GuestDish { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Shift> Shift { get; set; }
        public DbSet<ShiftStaff> ShiftStaff { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Table> Table { get; set; }
        public DbSet<Type> Type { get; set; }
    }
}
