//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvertimeCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Guest = new HashSet<Guest>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual ICollection<Guest> Guest { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
